### ISSUE TITLE
Try using IRC SASL auth to circumvent Freenode Blacklist of AWS IP addresses

### ISSUE THREAD

**Issue by ramiro** [django/ticketbot#11]
It seems this is the problem we are having.

See e.g. for other cases:

https://github.com/cnaude/PurpleIRC/issues/141

https://github.com/StackStorm-Exchange/stackstorm-irc/issues/1

We need the bot to be authenticated as its registered nick to be able to join our channels. But as Freenode doesn't allow it to even connect, it is isn't possible to even get it to lurk and receive private messages.

Freenode SASL docs: http://freenode.net/kb/answer/registration http://freenode.net/kb/answer/sasl

Unfortunately Twisted IRC doesn't have the ability to use SASL auth.

**Comment by shaib** [comment]
Back in 2010 I wrote a chatbot using python-purple, but I don't know if it is still maintained.

**Comment by ramiro** [comment]
I went ahead and deployed the PR branch to Heroku to actually test it can log in to Freenode from the dyno IP address. It seems to be working: The bot is now available in our channels.
